version: "3.8"
services:

  # scheduler:
  #   image: ocurrent/ocluster-scheduler:live
  #   command:
  #     - --secrets-dir=/capnp-secrets
  #     - --capnp-secret-key-file=/capnp-secrets/key.pem
  #     - --capnp-listen-address=tcp:0.0.0.0:9000
  #     - --capnp-public-address=tcp:scheduler:9000
  #     - --pools=linux-x86_64
  #     - --state-dir=/var/lib/ocluster-scheduler
  #     - --default-clients=ocaml-docs-ci
  #   init: true
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - 'scheduler-data:/var/lib/ocluster-scheduler'
  #     - 'capnp-secrets:/capnp-secrets'

  # worker:
  #   build:
  #     dockerfile: docker/worker/Dockerfile
  #     context: .
  #   command:
  #     - --connect=/capnp-secrets/pool-linux-x86_64.cap
  #     - --name=ocluster-worker
  #     - --allow-push=ocurrentbuilder/staging,ocurrent/opam-staging
  #     - --capacity=1
  #     - --state-dir=/var/lib/ocluster
  #     - --store=rsync:/var/cache/obuilder
  #     - --rsync-mode=hardlink
  #     - --obuilder-healthcheck=0
  #     - --verbose
  #   init: true
  #   privileged: true            # required for the Docker in Docker container to work
  #   restart: on-failure         # (wait for the scheduler to write the pool cap)
  #   volumes:
  #     - 'worker-data:/var/lib/ocluster'
  #     - '/var/run/docker.sock:/var/run/docker.sock'
  #     - 'capnp-secrets:/capnp-secrets:ro'
  #   environment:
  #     - DOCKER_BUILDKIT=1

  init:
    build:
      dockerfile: docker/init/Dockerfile
      context: .
    environment:
      - KEYFILE=/ssh/id_ed25519
      - KEYTYPE=ed25519
    volumes:
      - 'ssh-credentials:/ssh/'

  storage-server:
    build:
      dockerfile: docker/storage/Dockerfile
      context: .
    depends_on:
      - "init"
    ports:
      - "2222:22"
    volumes:
      - 'ssh-credentials:/root/.ssh/'
      - 'docs-data:/data'

  http-raw-live-website:
    restart: on-failure
    image: nginx
    command: >
      bash -c "rm -rf /usr/share/nginx/html
      && ln -s /data/html-live/html-raw /usr/share/nginx/html
      && nginx -g 'daemon off;'"
    ports:
        - "8002:8000"
    volumes:
      - 'docs-data:/data/'

  http-raw-current-website:
    restart: on-failure
    image: nginx
    command: >
      bash -c "rm -rf /usr/share/nginx/html
      && ln -s /data/html-current/html-raw /usr/share/nginx/html
      && nginx -g 'daemon off;'"
    ports:
        - "8003:8000"
    volumes:
      - 'docs-data:/data/'

  ocaml-docs-ci:
    # Use published docker container
    # image: ocurrent/docs-ci:live
    # Build from local sources
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - "storage-server"
      # - "scheduler"
      # - "worker"
    command:
      - --confirm=above-average
      - --ocluster-submission=/run/secrets/cluster_cap_file
      - --ssh-host=172.17.0.1 # ocluster jobs are spawned by the host's docker, so they don't have
                              # access to this docker-compose's network. therefore we have to get
                              # to the storage server through the host network.
      - --ssh-port=2222
      - --ssh-user=root
      - --ssh-privkey=/ssh/id_ed25519
      - --ssh-pubkey=/ssh/id_ed25519.pub
      - --ssh-folder=/data
      - --jobs=6
      - --limit=1               # Only build the most recent version of each package
      - --filter=capnp-rpc      # NOTE Only build capnp-rpc documentation.
    init: true
    restart: on-failure         # (wait for the scheduler to write the submission cap)
    ports:
      - 8080:8080 # HTTP UI
    volumes:
      - 'ocaml-docs-ci-data:/var/lib/ocurrent'
      - "capnp-secrets:/capnp-secrets"
      - 'ssh-credentials:/ssh/'
    environment:
      - OCAMLRUNPARAM=b
      - CI_PROFILE=docker
    secrets:
      - cluster_cap_file

volumes:
  ocaml-docs-ci-data:
  worker-data:
  scheduler-data:
  capnp-secrets:
  docs-data:
  ssh-credentials:

secrets:
  cluster_cap_file:
    file: ./capnp-secrets/submit-ocaml-docs-ci.cap
